### ISSUE TITLE
Credentials are stored per Windows user and SQ server, not per solution

### ISSUE THREAD

**Issue by michalb-sonar** [SonarSource/sonarlint-visualstudio#353] opened 2017-10-10 14:16 UTC
Repro:
1. Connect solution1 to SQ as user1.
2. Connect solution2 to the same SQ as user2.
3. Close VS, open solution1.

Result:
SQ connections is connecting as user2. Credential manager shows user2 credentials only.

This behaviour is quite unexpected. Not sure if there is a use case to have credentials per solution, but we should at least we warn that credentials are being overwritten.

Related Information:
    SonarLint for VS Version: Milestone 3.6
    Visual Studio Version: 2015u3

**Comment by duncanp-sonar** [comment] 2017-10-10 14:33
@michalb-sonar This is by design, isn't it? The data is stored in the credential manager per Windows user i.e. if two Windows users are sharing the same machine they will each have to provide a SQ user name+password.
For a single Windows user, I don't think we expect them to use different SQ accounts for the same SQ server.

**Comment by michalb-sonar** [comment] 2017-10-10 14:40
@duncanp-sonar from design point of view, it makes sense. I'm just not sure if users are aware of that behaviour, as it's not obvious.

**Comment by valhristov** [comment] 2017-10-10 15:06
We could provide UI to choose whether they want to use stored credentials or enter new. I doubt this is of high value though.

**Comment by michalb-sonar** [comment] 2017-10-10 15:09
Or a warning that the credentials will be replaced. I don't consider this a high priority ticket.

**Comment by duncanp-sonar** [comment] 2018-10-09 10:46
Closing as by design. We don't expect users to connect to SonarQube using multiple different SonarQube accounts.

**Closed by duncanp-sonar** 2018-10-09 10:46 UTC
Labels: Area: Connected Mode, Type: Improvement
