### ISSUE TITLE
Issue with RSPEC-4055

### ISSUE THREAD

**Issue by JaedenRuiner** [SonarSource/sonarlint-visualstudio#583] opened 2018-03-09 01:46 UTC
### Description

Despite the requirement to always use an overload with CultureInfo, IFormatProvider, or StringComparison, which defeats the purpose of an overload, especially when I'm providing the same defaults that the overload provides, there is a flaw when using Convert.ToInt32.

Convert.ToInt32 has an overload with the "fromBase" parameter, so that one can easily convert binary, octal, and specifically Hexadecimal strings to integers.  There is no overload that allows the providing of a fromBase and an IFormatProvider.  

I think this begs to question the entire "code smell" but that's me.  Pretty much all computers use the Arabic numerals, and regardless of Unicode, Hex is still 0-9,A-F there is no "culture" needed in interpreting those characters in modern PCs.  The IFormatProvider (especially when null) does not provide any benefit to conversion, yet silences the Rule.
Edit:
also with Control.DataBindings.Add(Binding) is unnecessary when the binding has the IFormatProvider on it's constructor.
### Repro steps

Please provide the steps required to reproduce the problem

1. do a Convert.ToInt32("FF03", 16);
2. do a Binding b = new Binding("Text", textbox1, "Data", true, DataSourceUpdateMode.OnPropertyChanged, null, null, null);
3. add a textBox1.DataBindings.Add(b); <-- here's the issue
4. Build.

### Expected behavior

If IFormatProvider is of benefit, like say for Convert.ToDateTime, which makes sense, by all means keep the analysis but converting a text to an integral type it becomes meaningless.  These conversions do not translate "One thousand, one hundred and fifty-two", they convert "12345" to an Int32, Int16, Int64 type.

### Actual behavior

I get a warning to use the overload with IFormatProvider when i need to parse a Hexidecimal number, without a valid overload to provide the three parameters.

### Known workarounds

Ignore or pragma

### Related information

* SonarLint for VS Version: 7.0.0.4784
* Visual Studio Version VS2015 Enterprise 14.0 Update 3
* SonarQube server version: 5.6.7
* Languages in your solution C#

**Comment by valhristov** [comment] 2018-03-09 08:05
@JaedenRuiner thanks for the feedback! I will close this bug as it looks exactly the same as #1083, let me know if you think it's different.

**Closed by valhristov** 2018-03-09 08:05 UTC

**Comment by JaedenRuiner** [comment] 2018-03-09 17:12
It's similar yes.  But I also was noting the Control.DataBindings.Add() flaw to mine.  if that belongs in a separate issue, let me know and I'll submit it.

**Comment by valhristov** [comment] 2018-03-12 08:46
I was not able to reproduce the problem with the following code (new WinForms app, code pasted in `Main()`):

```
var t = new TextBox();
var b = new Binding("Text", t, "Data", true, DataSourceUpdateMode.OnPropertyChanged, null, null, null);
t.DataBindings.Add(b); // This does not raise with latest SonarLint 7.0
```

To be frank, I am not sure where exactly to put the `Convert.ToInt32` and if it affects the issue. Could you update your answer with a code snippet?

Also, are you using connected mode in SonarLint? If the answer is yes, could you share the version of SonarC# that's installed on your SonarQube instance? (When in connected mode, SonarLint uses the rules that are built-into the SonarC# plugin installed on SonarQube, so  yours could be older an version where the problem have not been fixed yet)
