### ISSUE TITLE
Exception after startup: The 'OpenInIDEPackage' package did not load correctly

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonarlint-visualstudio#2737] opened 2021-11-02 07:28 UTC
### Version

SL 4.39.0.38793 DOGFOOD
VS 2019 16.11.4

### Description

Error #2736 is followed by 
The 'OpenInIDEPackage' package did not load correctly

### ActivityLog

```
SetSite failed for package [OpenInIDEPackage]Source: 'Microsoft.VisualStudio.Composition' Description: Expected 1 export(s) with contract name "SonarLint.VisualStudio.IssueVisualization.Security.OpenInIDE.Http.IHttpListenerFactory" but found 0 after applying applicable constraints. Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "SonarLint.VisualStudio.IssueVisualization.Security.OpenInIDE.Http.IHttpListenerFactory" but found 0 after applying applicable constraints.
at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(String contractName, ImportCardinality cardinality, Type type, Type metadataViewType, IMetadataViewProvider& metadataViewProvider)
at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)
at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()
at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
at SonarLint.VisualStudio.IssueVisualization.Security.OpenInIDE.OpenInIDEPackage.<InitializeAsync>d__3.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass16_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext() 
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
at Microsoft.VisualStudio.Services.VsTask.GetResult()
```

**Comment by Caedendi** [comment] 2021-11-24 09:00
I have this same issue. Have you found a workaround in the meantime or discovered which packages don't like SonarLint?

**Comment by pavel-mikula-sonarsource** [comment] 2021-11-24 09:19
@Caedendi my workaround was to migrate to VS 2022.

The problem seems like a corrupted MEF cache or VS installation data.

**Comment by duncanp-sonar** [comment] 2021-11-24 10:37
@Caedendi could you try clearing the MEF cache to see if that fixes it? (https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache will help).

If not, does uninstalling/reinstalling fix the problem?

**Comment by Caedendi** [comment] 2021-11-24 15:17
Some more clarification from my side:

- Laptop, Windows 10 Enterprise
- Installed Visual Studio versions:
  | VS | install info | Extensions | Problems |
  |-|-|-|-|
  | 2019 Community | existing, old | a bunch | none |
  | 2022 Community (Preview) | existing, few weeks old | a few (weren't ported yet | none |
  | 2022 Community | new/fresh, few weeks ago | all from 2019 where available, installed manually | error messages after installing SonarLint |
- Error messages:
  1. ![VS error 1 SonarLint](https://user-images.githubusercontent.com/8746835/143264691-ee991e4f-0bdb-4c59-b0a4-41647dbfa1a7.png)
  2. ![VS error 2 OpenInIDE](https://user-images.githubusercontent.com/8746835/143264735-85a144ec-a3d3-4ccb-92d0-985d668dbbe0.png)
 
I have installed the MEF cache extension mentioned above, restarted VS, cleared cache + restarted, but the messages still persist.
Uninstalling SonarLint made the messages disappear.

Do you have any use for my Activity Log mentioned in the error screenies?

**Comment by duncanp-sonar** [comment] 2021-11-24 15:32
@Caedendi if you can send it to me I'll take a look, although I'm not confident it will have much more detail. duncan dot pocklington at sonarsource dot com.

Could you reinstall the extension successfully after uninstalling it?
Thanks

**Comment by rita-sonarsource** [comment] 2021-12-15 13:33
@Caedendi we would like to follow up on this issue. Have you experienced this problem with recent versions of sonarlint? We've released a [new version](https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2022) yesterday, would you mind giving it a try and seeing if the issue still persists?

**Comment by rita-sonarsource** [comment] 2021-12-21 10:28
This issue is likely caused due to MEF cache corruption. We cannot reproduce it on our side, closing as can't reproduce. Please feel free to comment with additional details if this happens after re-installing the extension.

**Closed by rita-sonarsource** 2021-12-21 10:28 UTC
Labels: Type: Bug

**Comment by Caedendi** [comment] 2022-02-21 16:41
@rita-sonarsource 

Hi Rita,

I have since changed employers and now have a brand new laptop, brand new VS installation and license and I still run into this issue. I would like to provide you with all the details you need to reproduce this issue if you can tell me how.

My apologies for the late response.
