### ISSUE TITLE
[TFS] When syncing with SonarQube, SonarLint for VS should not touch files if there is no change #198

### ISSUE THREAD

**Issue by connectinghub** [SonarSource/sonarlint-visualstudio#635] opened 2018-05-03 10:09 UTC
### Description

Re-opening "When syncing with SonarQube, SonarLint for VS should not touch files if there is no change" #198

I am facing the exact same issue as reported by @csoltenborn in #198, where the ruleset files are "touched" and get checked-out automatically, even when then has been no change in the quality file on the server.

@Evangelink mentioned that this issue is no longer relevant in connected mode. However, I am able to replicate the issue with connected mode as well. 

Any help will be highly appreciated.

### Expected behavior

No files should get checked-out automatically when a solution that was previously binded to a quality file on SonarQube server is re-binded, even when there are no changes in the quality profile on the server. 

### Actual behaviour

All ruleset files, .sln file, .sqconfig file get checked-out automatically (solution-level and project-level) with no changes in them. 

### Related information

* VS version 15.3.4
* SonarLint version 3.10
* Languages in your solution (C#)

**Comment by csoltenborn** [comment] 2018-05-03 10:55
Same problem (still) over here - in fact, this is the main reason why our team does not use SonarQube.

**Comment by Pradeep1409Bora** [comment] 2019-01-09 15:51
Is it already fixed ?

Because I am using Sonar lint 4.7.0.3891 and still see this as well as we are also facing issues in updating the rules:- https://community.sonarsource.com/t/visual-studio-binding-always-throw-an-error/5688


We always have to delete the .slconfig file which is a bit annoying :(

**Comment by valhristov** [comment] 2019-01-09 16:17
No, the ticket is still open :)

**Comment by duncanp-sonar** [comment] 2019-01-16 18:17
### Update

I've tested with VS2015, VS2017 and TFS Express 2015 and I haven't managed to repro this bug.

The last-written timestamp for some of the files is changed, but VS correctly detects that the content is the same so the file does not appear in the list of _Pending Changes_ (the project files do appear briefly in the Solution Explorer with a "changed" glyph, which then changes back to the normal unchanged/locked glyph).

### Next steps
I'm going to mark the bug as _Cannot reproduce_. If anyone can provide more information to help us repro the bug we'd be very grateful. Otherwise, we'll close it in a few weeks (it can always be re-opened in the future).

#### Useful additional information:
* which version of TFS does this occur with, and which SCC option i.e. Git or TfVC?
* could the file encoding on the local machine be different from the one used in source control? (I tried changing the file encoding and file endings locally, and it was obvious when comparing the files in VS that there was a difference)
* any other suggestions?


### Notes on testing carried out
FYI More detail on the scenarios I tested:

#### Versions used
VS2015 Update 3, VS2017 v15.9
TFS Express 2015

#### Scenarios tested (all using legacy connected mode)
1. Update binding -> no pending changes

2. Change QP on server then update binding
	-> SolutionBinding.sqconfig and xxxCSharp.ruleset appear as Pending Changes (expected).
	-> no other Pending Changes, although the timestamps on the individual project files and project-level rulesets have changed.

3. Change the version of SonarC# plugin installed on the server
	-> new version of SonarC# NuGet installed
		-> all project files and packages.config files updated (expected)
		-> generated xxxCSharp.ruleset changes (expected, new rules added in new version of the plugin)
		-> new version of the SonarC# packages under the packages folder, appears as an Excluded change (expected)
		-> no other pending changes

**Comment by rita-g-sonarsource** [comment] 2020-07-07 08:51
Closing as there was no additional information from the community. For future reference, please see this comment: https://github.com/SonarSource/sonarlint-visualstudio/issues/635#issuecomment-454884052

**Closed by rita-g-sonarsource** 2020-07-07 08:51 UTC
Labels: Area: Connected Mode, Community, Status: Cannot reproduce, Status: On Hold
