### ISSUE TITLE
Allow validate test projects

### ISSUE THREAD

**Issue by NikitaEgorov** [SonarSource/sonarlint-visualstudio#197] opened 2017-05-26 13:11 UTC
### Description

Allow validate code style in test projects

### Repro steps

1. Create solution with test project

2. Install SonarLint

3. No checks in test projects

**Comment by rita-g-sonarsource** [comment] 2020-07-07 09:14
Duplicate of #632

**Closed by rita-g-sonarsource** 2020-07-07 09:14 UTC
