### ISSUE TITLE
Remove use of UIDispatcher.BeginInvoke

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#2792] opened 2021-11-25 15:48 UTC
### Description

Some of older code in SLVS uses threading techniques that are no longer supported/appropriate in VS. One example is `IHost.UIDispatcher.BeginInvoke`  

VSTHRD110 warns about using this API: _Await JoinableTaskFactory.SwitchToMainThreadAsync() to switch to the UI thread instead of APIs that can deadlock or require specifying a priority._

Potentially related issue: #2791

#### Notes

`UIDispatcher.BeginInvoke` is only used in three places in the code.

There are a number of uses of `UIDispatcher.CheckAccess` which should be replaced with e.g. our test-friendly `IThreadHandling.CheckAccess`. It should then be possible to remove `IHost.UIDispatcher` completely.

Current SLVS version: v 5.1

**Comment by bigfluffycookie** [comment] 2022-11-23 11:06
Duplicate of #3213

**Closed by bigfluffycookie** 2022-11-23 11:06 UTC
Labels: Duplicate, Performance
