### ISSUE TITLE
Rules with max value not been loaded from SonarQube Project

### ISSUE THREAD

**Issue by simon2017** [SonarSource/sonarlint-visualstudio#815] opened 2019-02-13 16:03 UTC
### Description

Sonarlint rule analysis is not been based on the SonarQube server's rule max parameter

### Repro steps
1. For rule csharpsquid:S1200, having a Sonarqube server set max permited dependecies of 20.
2. Connect Visual Studio 2017 with SonarQube project using SonarLint.
3. In Visual Studio create a source code with a dependencie major of 30.
4.- Analyze source code using Sonarlint.
5.- Analyze source code using SonarQube Project

## Result
SonarLint will raise a S1200  warning because code exceeds the max permitted dependencies of "30", but SonarQube server will raise error notifying a max of 20.

* SonarLint for VS Version 4.8.0.4040
* Visual Studio Version 15.9.6
* SonarQube server version  6.7.5 (build 38563) Community
* Languages in solution C#

**Comment by duncanp-sonar** [comment] 2019-02-13 17:23
This is a duplicate of https://github.com/SonarSource/sonarlint-visualstudio/issues/176, which also describes a manual workaround.

**Closed** 2019-02-14 16:01 UTC
