### ISSUE TITLE
Enable connected mode for .Net Core projects

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonarlint-visualstudio#151] opened 2017-04-27 16:01 UTC
Currently it is not possible to used connected mode to analyse .Net core projects.

Contributes to [MMF-876](https://jira.sonarsource.com/browse/MMF-876).
Is duplicated by [SVS-151](https://jira.sonarsource.com/browse/SVS-151).

**Comment by Evangelink** [comment] 2017-05-01 15:53
ProjectTypeGuid for .Net Core Console: `8BB2217D-0F2D-49D1-97BC-3654ED321F3B`

**Comment by TangAgapes** [comment] 2017-05-09 07:09
Hi,

Saw this feature planned for milestone 2.14, now planned for 3.0. 
Is there any chance to get this feature in coming days/weeks ?
My team is starting to use .Net Core for new projects, and would be great to get this feature soon, there's no emergency for us to get it, but if we have to wait for month, we will not wait, and try the workaround posted before.
So any idea on the schedulle of this feature ?

Thanks a lot for your work

**Comment by Evangelink** [comment] 2017-05-09 07:28
Hi @TangAgapes,
You are right this was originally planned for 2.14 (that we changed into 3.0) but after some investigations the solution seems to be a bit more complex than expected (especially to fully support C#7 syntax).

**Comment by NeilCross** [comment] 2017-05-11 22:28
Cheers for the update, any rough indications on the timelines we could expect as this issue has no milestone assigned currently?

**Comment by ed11s8c** [comment] 2017-06-05 15:19
@Evangelink Is there any news for this task? It seems to have been pushed back several times over the last couple of months. Its a real pain when .Net Core is now stable so will be used by many for new projects going forward.

**Comment by mracz** [comment] 2017-07-21 14:24
@Evangelink Could you please give any update on ETA of the fix for this issue? We heavily rely on .NET Core projects and we would like to utilize SonarLint. Thanks!

**Comment by Evangelink** [comment] 2017-07-21 15:00
@TangAgapes @NeilCross @ed11s8c @mracz Hi guys, we know that this feature is really important for you and we haven't forgotten about it but we cannot commit to a release date at this point. We definitely hope to have this done by Q4 but I can't be any more specific than that.

**Comment by TheYorkshireDev** [comment] 2017-08-17 13:26
@Evangelink Will you be developing the integration of SonarQube for the newly released .Net Core 2.0 only or will you also be developing with support for .Net Core 1.0 & 1.1 too?

**Comment by Evangelink** [comment] 2017-08-17 13:35
@TheYorkshireDev I don't know yet but my gut feeling is that we will support only .Net Core 2+

**Comment by Robak23** [comment] 2017-09-20 11:55
@Evangelink Any ETA for resolving this issue?

**Comment by Evangelink** [comment] 2017-09-20 16:27
@Robak23 I am tempted to answer still on time but to be fair we only did one step forward for now (moving the analyzers to .net core - unpublished for now).

**Comment by Robak23** [comment] 2017-09-21 09:07
@Evangelink  Thank you for the answer. I look forward to your updates on that issue.

**Comment by abhishekbdutta** [comment] 2017-10-25 09:50
Hello @Evangelink can you please tell us some probable dates, would be very nice.

**Comment by lazyspark** [comment] 2017-11-01 13:57
Is this up for grabs. Please let us know if anyone can help towards resolving this.

**Comment by Evangelink** [comment] 2017-11-02 16:11
Hi guys,
We expect to be able to provide the support for .Net Core projects in SonarLint connected mode by the end of next week.

**Closed** 2017-11-15 16:45 UTC
Labels: Area: Connected Mode, Area: VS2017, Type: New Feature

**Comment by abhishekbdutta** [comment] 2017-12-14 04:28
The connected mode is working but the rules which are configured as errors on the severs are shown as warnings in the rule set in visual studio

Sonar lint: 3.8
SonarQube server: 6.7
Sonarc# Analyzer on server: 6.6 (build 3969)

**Comment by valhristov** [comment] 2017-12-14 08:06
@abhishekbdutta that's by design and applies to all languages and IDEs - if the rules in VS were configured as errors we would break your build and we don't want to do that.

**Comment by abhishekbdutta** [comment] 2017-12-15 13:11
@valhristov thanks for the reply, but i have some concerns
The one of objective of putting the sonarqube in an organization is to have a set of rules consistent across all the teams. These rules are part of quality gates.
This means that the server will report errors and stop by CI process. The developer needs to fix these ASAP.

In this given case if they are configured as error in VS then the above uses case wont come right ?

**Comment by valhristov** [comment] 2017-12-15 13:27
@abhishekbdutta that's correct, but imagine a project that contains hundreds (or thousands) of issues - you will have to fix them all immediately after installing SonarLint because otherwise you will not be able to work. We want to avoid that. The developers should be able to ignore the old issues (e.g. the technical debt) and fix them little by little. In addition, sometimes it might be required to add new debt, for example to quickly provide a version to the QAs to test.

By the way, the Scanner for MSBuild will also turn off TreatWarningsAsErrors, so CI will not be broken even if you commit not very clean code.

The general recommendation is to enforce clean code through quality gates or code reviews (which is a good practice even without SonarQube).
