### ISSUE TITLE
Visual Studio does not update all rules after synchronisation with SonarQube

### ISSUE THREAD

**Issue by cam92yz** [SonarSource/sonarlint-visualstudio#843] opened 2019-03-21 09:22 UTC
### Description

SonarLint creates after synchronisation with SonarQube for every projects a ruleset file that point to a shared ruleset file.

Something like this:

```
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="SonarQube - Backend Sonar way 2" ToolsVersion="15.0">
  <Include Path="..\.sonarlint\shared.ruleset" Action="Default" />
</RuleSet>
```

In the shared file there are all synchronized rules listed. Synchronization of this list works properly. After synchronization with SoarQube, all rules are synchronized as expected.

But in the “Active Rule Set Window” in Visual Studio (References -> Analyzers -> Open Active Rule Set) not all rules did update to the new state. Some of the rules got updated properly for example rule S100, but some rules for example rule S101 did not change the state to the new state although it has synchronized the correct state in the shared ruleset file. 

Rules that are defined directly in the included rulset file of the project (like in the example below S101, S1006) dont't  have this problem,

For example, is rule s100 set to none (like in the example below) in the direct included ruleset file of the project, it will change the state in the “active rule set window of VS” to the correct state. Is the rule set in the shared file to none (in the shared.ruleset file in the example code below ) it does not change the state in "the active rule set" window.

```
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="SonarQube - Backend Sonar way 2" ToolsVersion="15.0">
  <Include Path="..\.sonarlint\shared.ruleset" Action="Default" />
    <Rules AnalyzerId="SonarAnalyzer.CSharp" RuleNamespace="SonarAnalyzer.CSharp">
		<Rule Id="S1006" Action="None" />
		<Rule Id="S101" Action="None" />
	</rules>
</RuleSet>
```

I assume that the rules that are set by default to warning by SonarLint override the state of the rules in the shared file so that it is impossible to change the state of this rules over synchronization because the synchronization writes the rules and their state in a shared file instead in a direct included file of the project.

I expect that after synchronization all rules have the the same state like on the SonarQube server.

### Related information

* SonarLint for VS Version 4.8.0.4040
* Visual Studio Version (Enterprise 2017 15.9.7)
* Language: C#

**Comment by duncanp-sonar** [comment] 2019-03-21 15:11
The expected behaviour of SonarLint in relation to rulesets is not straightforward and isn't currently documented (although I hope to address this in #775 soon).

The original aim of the feature was as follows: for connected mode, the set of rules used in Visual Studio should be the ones configured in the Quality Profile for the project in SonarQube. However, it should also be possible for developers to configure other Roslyn analysers in their projects, and also to _strengthen_, but not weaken, the set of rules configured in the Quality Profile (e.g. turn on more rules locally, or increase the severity of certain rules).

That's why there is a per-project ruleset and a shared ruleset. The shared ruleset is the one that is synchronised with the QP in SonarQube. The per-project ruleset is the one that allows developers to configure rules for other analysers. It imports the shared ruleset as a starting point.

If a rule appears in both the per-project ruleset and the imported shared ruleset then the setting in the local ruleset wins. Tthat's how Visual Studio decides what the effective set of rules is.
So, if you change the set of rules using the editor in VS, it will save those changes in the per-project ruleset and they will take precedence over whatever is specified in the shared ruleset.

To prevent the user from weakening the effective ruleset (e.g. by turning off rules that are in the Quality Profile), SonarLint will periodically do a check on the effective ruleset. If any rule that is in Quality Profile is set to a lower severity or turned off, SonarLint will display a warning gold bar in the Error List saying the ruleset needs to be updated.

That's been the behaviour of SonarLint for Visual Studio since it was first released.
However, it is rather complicated and isn't in step with how SonarLint behaves in other IDEs such as IntelliJ and Eclipse. There are a number of tickets in this repo intended to simplify the behaviour e.g. #817 (stop generating the project ruleset and directly import the shared ruleset) and #790 (correctly detect when the shared ruleset is imported - already done).

What you can do now in (since SLVS v4.8) is manually delete the per-project rulesets, and directly reference the shared ruleset from inside each MSBuild project. That addresses part of the problem you describe - after the synchronisation, the set of rules applied will be the ones specified in the Quality Profile. This will become the default behaviour when #817 is implemented.

A further issue is that the generated shared ruleset should use the severities specified in the Quality Profile. That's the subject of the open ticket #808.

**Comment by cam92yz** [comment] 2019-03-21 16:00
Thank you for your answer.

I am not sure whether you understood me correctly. The Problem is that some rules don't get updated even if there is no entry for the rule in the per-project ruleset that could override the rule in the shared file.

This is my shared file: 
Rule S101 is set to none

![1](https://user-images.githubusercontent.com/48785301/54765181-55353100-4bf9-11e9-8672-d7b9dd96ca87.PNG)

This is my per-project ruleset. Here are no other rules defined.

![2](https://user-images.githubusercontent.com/48785301/54765207-60885c80-4bf9-11e9-9caf-d765eea495f1.PNG)

Here is rule S101 still active although the rule is set to none in the shared file and there are no rules in the per-project ruleset defined that could override the rules in the shared file.

![3](https://user-images.githubusercontent.com/48785301/54765318-93325500-4bf9-11e9-85f2-d57796f9b383.PNG)

But this problem does not occur with all rules. For example, rule S100 does not have this problem. (The same example with rule S100 would work properly)

**Comment by duncanp-sonar** [comment] 2019-03-21 16:44
It sounds like the shared ruleset is being generated correctly, and included in the per-project ruleset using the `Default` action as expected. According to [this doc](https://github.com/dotnet/roslyn/blob/master/docs/compilers/Rule%20Set%20Format.md#include) from Microsoft, that should mean that the individual rule actions specified in the included ruleset should be used.

Visual Studio is responsible for calculating the effective ruleset, based on the contents of the per-project ruleset and any rulesets it imports. If the VS ruleset editor isn't showing the expected results then that's an issue with Visual Studio, not with SonarLint.
Does the ruleset editor show the correct results if you close and reopen the solution (or unload and reload VS)?

**Comment by cam92yz** [comment] 2019-03-22 08:57
No, reopen the solution does not solve the problem.
I guess you also use Visual Studio. You don't have the bug?
I assume the problem only occurs for those rules that have set warning by default in SonarLint.

**Comment by VladimirZD** [comment] 2019-04-25 10:51
I have same issue.
For example i took rule S2325, which by default is minor, changed it to blocker.
After analyzing project in Sonar, it shows  issues regarding that rule as blockers.
But when i open visual studio (i have done multiple restarts) it is still warning.

I was expecting that it will be showed as error. I am i wrong?

Thnx

**Comment by duncanp-sonar** [comment] 2019-06-04 15:27
@VladimirZD currently the ruleset generated from QP sets the severity to _None_ or _Warning_ - see #808

**Comment by duncanp-sonar** [comment] 2023-08-17 10:47
Closing as obsolete. Since v7, SLVS generates global `.editorconfig` files. It no longer generates `ruleset` files, and no longer makes changes to any project files.

**Closed by duncanp-sonar** 2023-08-17 10:47 UTC
