### ISSUE TITLE
Null reference exception occurs on project load if SonarQube is not accessible

### ISSUE THREAD

**Issue by chrsmrtn-** [SonarSource/sonarlint-visualstudio#2415] opened 2021-05-12 16:38 UTC
### Description

If I start my project before I launch my VPN (which allows my VS instance to see the SonarQube server) I get the following error popup:

The 'TaintSyncPackage' did not load properly

In inspecting the ActivityLog.xml file i see the following stack trace:

SetSite failed for package [TaintSyncPackage]Source: &apos;SonarLint.VisualStudio.IssueVisualization.Security&apos; Description: Object reference not set to an instance of an object.&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintIssuesSynchronizer.IsFeatureSupported()&#x000D;&#x000A;   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintIssuesSynchronizer.&lt;SynchronizeWithServer&gt;d__10.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintSyncPackage.&lt;InitializeAsync&gt;d__1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass16_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__70.MoveNext()</description>
    <guid>{EEEB81FA-D6C3-438D-B29E-9FAAC91471CC}

### Repro steps

Launch a project that is linked to the SonarQube server while the SonarQube server is unavailable.

### Expected behavior

The plugin to gracefully handle this situation.

### Actual behavior

The above popup is displayed and the null reference exception is logged to the ActivityLog.xml file.

### Known workarounds

Ensure your computer can see the SonarQube server before launching the project

### Related information

* SonarLint for VS Version: 4.34.0.31639
* Visual Studio Version: 16.0
* SonarQube server version: 6.1
* Languages in your solution: C#

**Comment by rita-sonarsource** [comment] 2021-05-12 16:54
Thank you for reporting this @chrsmrtn-.
This is a known issue and will be fixed in the upcoming release.
Closing as duplicate of #2287.

**Closed by rita-sonarsource** 2021-05-12 16:54 UTC
