### ISSUE TITLE
Goldbar is shown when analyzing CPP file on a slow machine

### ISSUE THREAD

**Issue by rita-g-sonarsource** [SonarSource/sonarlint-visualstudio#1277] opened 2020-03-18 10:23 UTC
### Description

When a CPP file is analyzed on a slow machine, a goldbar appears that SonarLint is affecting VS performance.

### Repro steps

1. Launch VS
2. Open the project
3. Open a series of files in the editor, one by one, while the computer is slowed down a lot (just opening the file takes several seconds, with some UI freezes).

### Expected behavior

No goldbar.

### Actual behavior

Goldbar appears.

![image](https://user-images.githubusercontent.com/60586879/76950909-110f6600-690b-11ea-8801-47fbe1e7c5e7.png)

### Known workarounds

None.

### Related information

* SonarLint 4.19 for VS 2019

OUTPUT LOG:
Using default daemon download URL
Daemon version: 4.3.2.2521
Daemon download url: https://binaries.sonarsource.com/Distribution/sonarlint-daemon/sonarlint-daemon-4.3.2.2521-windows.zip
Settings file does not exist at "C:\Users\loica\AppData\Roaming\SonarLint for Visual Studio\settings.json".
Default settings will be used
No user-specified rule settings - using defaults
Analyzing C:\Dev\sonar-cpp\src\core\AnalyzerASTConsumer.cpp
WARNING: Timed out after waiting 10000 ms for process C:\USERS\LOICA\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\16.0_9A04DFC4\EXTENSIONS\KQSDW2WA.NQN\lib\subprocess.exe to complete: it has been terminated, but its child processes may still be running.
Initializing the telemetry package...
Finished initializing the telemetry package...
Initializing the notifications package...
Not connected: not checking for notifications
Finished initializing the notifications package
Initializing the daemon package...
Finished initializing the daemon package.
Saving notifications settings...
Saving notifications settings...
Saving notifications settings...

**Comment by gjactat** [comment] 2020-04-08 12:43
Hello,
Same here with a pretty large C# solution.
Event with no file opened at all. The simple fact of opening the solution makes SonarLint hang for 19 seconds.
I understand that SonarLinat has a lot to process during startup. Could this work be done asynchronously ?

![image](https://user-images.githubusercontent.com/1826064/78785314-40b00c00-79a7-11ea-8987-d8fea0e38ee9.png)

**Comment by duncanp-sonar** [comment] 2020-04-08 15:48
@gjactat thanks for reporting this.
I've created a separate issue (#1318) to track your scenario since although the symptoms are the same (gold bar) it's likely the root causes are different. This issue is about a perf impact that happens post-initialisation when analysing multiple C++ files.

I'l delete this comment and your comment from this thread in a couple of days to avoid any later confusion about the scope of this ticket.

**Comment by abbas-sabra-sonarsource** [comment] 2020-04-14 18:38
As discussed with @duncanp-sonar we decided to close this issue since we couldn't reproduce it. In general, to avoid the golden bar we should move things that can be done outside the UI thread to other threads. This will be done incrementally and separately by migrating code than doesn't need to run on UI thread. For example, there is a plan to move UI independent connected mode code to another thread. Note that most CreateRequest parts need to be done from the UI thread since DTE is being used.

**Closed** 2020-04-14 18:38 UTC
Labels: Language: CFamily, Type: Bug
