### ISSUE TITLE
Analysis exception when reading analysis results

### ISSUE THREAD

**Issue by loic-joly-sonarsource** [SonarSource/sonarlint-visualstudio#2482] opened 2021-07-08 23:22 UTC
### Description

I analyzed the following code:
```
int f(int* i)
{
  return *i;
}

int main(int argc, char** argv)
{
  int x;
  return f(&x);
}
```
SonarLint crashed

### Actual behavior

The following call stack get displayed:
```
Analyzing C:\Dev\sonar-cpp\src\core\analyzers\BitwiseComplementLeftshiftTypeCheck.cpp
Failed to analyze C:\Dev\sonar-cpp\src\core\analyzers\BitwiseComplementLeftshiftTypeCheck.cpp: System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Microsoft.VisualStudio.Text.SnapshotSpan.TranslateTo(ITextSnapshot targetSnapshot, SpanTrackingMode spanTrackingMode)
   à SonarLint.VisualStudio.Integration.Vsix.TextBufferIssueTracker.<>c__DisplayClass22_0.<TranslateSpans>b__1(IAnalysisIssueVisualization x)
   à System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   à System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   à System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   à System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   à SonarLint.VisualStudio.Integration.Vsix.TextBufferIssueTracker.TranslateSpans(IEnumerable`1 issues, ITextSnapshot activeSnapshot)
   à SonarLint.VisualStudio.Integration.Vsix.TextBufferIssueTracker.HandleNewIssues(IEnumerable`1 issues)
   à SonarLint.VisualStudio.Integration.Vsix.AccumulatingIssueConsumer.Accept(String path, IEnumerable`1 issues)
   à SonarLint.VisualStudio.Integration.Vsix.CFamily.CLangAnalyzer.HandleMessage(Message message, Request request, IIssueConsumer consumer, Int32& issueCount)
   à SonarLint.VisualStudio.Integration.Vsix.CFamily.CLangAnalyzer.<>c__DisplayClass14_0.<TriggerAnalysisAsync>b__1(Message message)
   à SonarLint.VisualStudio.Integration.Vsix.CFamily.Protocol.Read(BinaryReader reader, Action`1 handleIssue, String issueFilePath)
   à SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.<>c__DisplayClass21_0.<CallClangAnalyzer>b__1(StreamReader reader)
   à SonarLint.VisualStudio.Integration.Vsix.CFamily.ProcessRunner.Execute(ProcessRunnerArguments runnerArgs)
   à SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.CallClangAnalyzer(Action`1 handleMessage, Request request, IProcessRunner runner, ILogger logger, CancellationToken cancellationToken)
   à SonarLint.VisualStudio.Integration.Vsix.CFamily.CLangAnalyzer.CallSubProcess(Action`1 handleMessage, Request request, ISonarLintSettings settings, ILogger logger, CancellationToken cancellationToken)
   à SonarLint.VisualStudio.Integration.Vsix.CFamily.CLangAnalyzer.<TriggerAnalysisAsync>d__14.MoveNext()
ERROR: LLVM ERROR: IO failure on output stream: invalid argument

```

### Related information
Running the analysis outside of SonarLint did not trigger any issue.
Copying this in another project in another instance of VS still triggered the issue.

* SonarLint for VS Version: 4.36.0.34265
* Visual Studio Version : 2019 16.10 entreprise
* Languages in your solution (C, C++)

**Comment by rita-sonarsource** [comment] 2021-07-12 20:39
Closing as duplicate of #2276

**Closed by rita-sonarsource** 2021-07-12 20:39 UTC
Labels: Language: CFamily, Type: Bug
