### ISSUE TITLE
How to re-connect to a different SonarQube server

### ISSUE THREAD

**Issue by mayureshs** [SonarSource/sonarlint-visualstudio#1089] opened 2019-11-14 21:08 UTC
After downloading the VS2019 extension I had the configuration set to a test-ing sonar qube server. Now that we have moved to production how do I change the connection and re-enter credentials ? Thanks!

**Comment by duncanp-sonar** [comment] 2019-11-18 13:46
Closing as a duplicate of [this Community forum question](https://community.sonarsource.com/t/reconnect-sonarlint-to-a-different-sonarqube-server/16660).

**Closed by duncanp-sonar** 2019-11-18 13:46 UTC
Labels: Support
