### ISSUE TITLE
SonarQube not loading projects for private organization

### ISSUE THREAD

**Issue by PedroC88** [SonarSource/sonarlint-visualstudio#772] opened 2018-12-11 13:48 UTC
### Description
Projects aren't being loaded for my private Organization. I connect to SonarQube using my dev azure email account and a token. The organization has two projects that I can see and access in SonarCloud.

### Repro steps
1. Go to Manage SonarQube Connections
2. Click on _Connect..._
3. Type in my credentials (tried both, dev azure email and token as password, and token only)
4. Select my Organization from the list

### Expected behavior
After selecting the organization I expect that my Organization's project show up in the list.

### Actual behavior
No project is loaded
![image](https://user-images.githubusercontent.com/6889567/49803956-ba8aa380-fd27-11e8-944e-45e93615b105.png)

### Related information
* SonarLint for VS Version 4.7.0.3891
* Visual Studio Version Enterprise v15.9.3
* Connected to a private Organization in SonarCloud
* Languages in your solution: C#

**Comment by valhristov** [comment] 2019-01-07 12:35
A workaround for this problem: use `https://sonarcloud.io` instead of `https://www.sonarcloud.io`.

The latter redirects to the first and since the HttpClient [strips the Authentication header](https://blogs.msdn.microsoft.com/paulking/2011/03/31/how-to-lose-your-authorization-header-with-a-bad-url/) from the second request, the API call to Sonarcloud is not authenticated and returns only the public projects in your organization.

**Comment by PedroC88** [comment] 2019-01-07 13:35
I don't have a proxy and there should't be anything blocking that URL, I can also access the URL in the browser. This is the output which is pointing to a credentials issue, but I'm using the same credentials as with the _www_ and is failing, the credentials are my dev azure email plus a token.

`Connecting to SonarQube server: https://sonarcloud.io/`
`Connecting to SonarQube server: Validating credentials`
`SonarQube request failed: Invalid credentials`
`Connecting to SonarQube server: Failed`

**Comment by valhristov** [comment] 2019-01-07 14:03
I would like to keep the ticket open, there is a way to fix the problem on our side, but it will require some testing...

**Comment by PedroC88** [comment] 2019-01-07 14:21
Noted, thanks!

**Comment by valhristov** [comment] 2019-01-07 14:33
You are welcome, thanks for the quick confirmation!

**Comment by valhristov** [comment] 2019-01-14 13:12
Duplicate of #796

**Closed by valhristov** 2019-01-14 13:12 UTC
Labels: Status: In Progress
